name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install the package with dev dependencies
          pip install -e ".[dev]"

      - name: Run black
        run: |
          black --check $(git ls-files '*.py')

      - name: Run isort
        if: always()
        run: |
          isort --check --profile black $(git ls-files '*.py')

      - name: Run mypy
        if: always()
        run: |
          mypy $(git ls-files '*.py')

      - name: Run ruff
        if: always()
        run: |
          ruff check $(git ls-files '*.py')
